Repository wecode-bootcamp-korea/38-1st-JustWeDoIt-frontend, pull requests merged in 2022-10, with the labels that each got.

#2 [38기 정현석] footer 피드백 부분 수정 완료
  src/Router.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: Conflict 해결 요청

#8 [38기 최현] hotfix / cart, footer, stylelint 핫픽스 적용
  .stylelintrc.js
  package-lock.json
  package.json
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/ProductList/ProductList.scss
Labels: 멘토 리뷰 요청

#5 [38기 강은지] FIX: 수정 사항 반영 완료
  .stylelintrc.js
  public/data/1.png
  public/data/mock.json
  public/images/2.png
  public/images/logo.png
  src/Router.js
  src/components/Footer/Footer.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/NavModal/NavModal.js
  src/components/NavModal/NavModal.scss
  src/pages/Cart/Cart.scss
  src/pages/ProductList/ProductList.scss
  src/styles/mixin.scss
  src/styles/variables.scss
Labels: 완료

#15 [38기 강은지] ADD: 유틸함수 추가, config.js 파일 추가
  src/config.js
  src/utils/utilFunc.js
Labels: 멘토 리뷰 요청

#10 [38기 정현석]Product-Aside 아코디언 메뉴 구성 & Aside 레이아웃
  src/pages/ProductList/ProductAside.js
  src/pages/ProductList/ProductAside.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
Labels: 멘토 리뷰 요청

#9 [38 최현] 장바구니 - CRD
  public/data/CartMockData.json
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartItem.js
  src/pages/Cart/CartItem.scss
  src/pages/Cart/CartItemList.js
  src/pages/Cart/CartItemList.scss
  src/pages/Cart/CartSummary.js
  src/pages/Cart/CartSummary.scss
Labels: 멘토 리뷰 요청

#13 [38기 강은지] MODIFY: navModal 수정사항반영완료
  src/Router.js
  src/components/Nav/Nav.js
  src/components/NavModal/NavModal.js
  src/components/NavModal/NavModal.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: 멘토 리뷰 요청

#4 [38기 김민경]input 관련 기능구현
  src/components/Auth/Input/Input.js
  src/components/Auth/Input/Input.scss
  src/components/Auth/Input/InputLabel.js
  src/components/Auth/Input/InputLabel.scss
  src/components/Auth/Input/InputPassword.js
  src/components/Auth/Input/InputPassword.scss
  src/pages/SignIn/SignIn.js
  src/pages/SignIn/SignIn.scss
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
Labels: 완료

#11 [38기 강은지]MODIFY: 상세페이지 수정사항 반영완료
  src/components/ProductAccordianMenu/AccordianMenu/AccordianMenu.js
  src/components/ProductAccordianMenu/AccordianMenu/AccordianMenu.scss
  src/components/ProductAccordianMenu/ListItem/ListItem.js
  src/components/ProductAccordianMenu/ListItem/ListItem.scss
  src/components/ProductDetailBtn/ProductDetailBtn.js
  src/components/ProductDetailBtn/ProductDetailBtn.scss
  src/components/PurchaseModal/PurchaseModal.js
  src/components/PurchaseModal/PurchaseModal.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductList/ProductList.js
  src/styles/common.scss
Labels: 멘토 리뷰 요청

#16 [38기 정현석] 메인페이지 - 무한스크롤
  src/pages/ProductList/ProductList.js
Labels: 완료

#14 [38기 강은지] carousel 수정사항 반영완료
  src/components/Carousel/Carousel.js
  src/components/Carousel/Carousel.scss
  src/pages/Cart/Cart.js
Labels: 완료

#19 [38기 김민경] router 재수정 -main 중복 제거
  src/Router.js
Labels: 멘토 리뷰 요청

#18 [38기 최현] 장바구니 - UPDATE
  public/data/CartMockData.json
  src/pages/Cart/Cart.js
  src/pages/Cart/CartItem.js
  src/pages/Cart/CartItem.scss
  src/pages/Cart/CartList.js
  src/pages/Cart/CartList.scss
  src/pages/Cart/CartSummary.js
Labels: 완료

#20 [38기 강은지] Hotfix: Nav 컴포넌트 - link to 수정
  src/components/Nav/Nav.js
  src/components/NavModal/NavModal.scss
Labels: 완료

#21 [38기 김민경]main페이지 fetch 이슈 useeffect 사용하여 수정
  src/pages/Main/Main.js
Labels: 멘토 리뷰 요청

#17 [38기 정현석] 메인 페이지 - 무한 스크롤 & productlist 페이지에서 productdetail 페이지로 이동
  src/pages/ProductList/Product/Dropdown.js
  src/pages/ProductList/ProductList.js
Labels: 완료

#23 [38기 김민경] input창 추가구현 완료
  src/components/Auth/Input/Input.js
  src/components/Auth/Input/InputLabel.js
  src/components/Auth/Input/InputLabel.scss
  src/components/Auth/Input/InputPassword.js
  src/components/Auth/Input/InputPassword.scss
  src/components/Auth/Input/InputRULES.js
  src/pages/SignIn/SignIn.js
  src/pages/SignUp/SignUp.js
Labels: 멘토 리뷰 요청, 수정 요청

#25 [38기 강은지] Hotfix: 메인페이지 - 캐러셀 추가
  src/components/Card/Card.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: 멘토 리뷰 요청

#24 [38기 최현] payment창 layout
  src/Router.js
  src/pages/Payment/Payment.js
  src/pages/Payment/Payment.scss
  src/pages/Payment/PaymentInput.jsx
  src/pages/Payment/PaymentInput.scss
  src/pages/Payment/PaymentSummary.jsx
  src/pages/Payment/PaymentSummary.scss
Labels: 완료

#26 [38기 정현석] 메인 페이지 - Aside & header 필터링 (PR 17 을 따라감)
  src/components/Footer/Footer.js
  src/pages/ProductList/ProductAside.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
Labels: 완료
